swagger: "2.0"
info:
  description: "3dモデルの中身のmeta情報を取得するためのAPI"
  version: "0.1.0"
  title: "VrmRipperAPI"
host: "qv2p534cl3.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /ripper/vrm:
    get:
      summary: "VRM ファイルの中身のJSONを抽出する"
      description: "Multiple status values can be provided with comma separated strings"
      produces:
      - "application/json"
      parameters:
      - name: "url"
        in: "query"
        description: "VRMファイルのURL"
        required: true
      responses:
        200:
          description: "successful"
          schema:
            type: "object"
